sudo: required
services:
- docker

before_install:
- docker pull dpollet/texlive:pillar

script: |
  docker run --tty --rm --volume $PWD:/work dpollet/texlive:pillar bash -c "\
    wget --quiet --output-document=- 'https://raw.githubusercontent.com/pillar-markup/pillar/master/download.sh' | bash \
    && make book "

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-Infrastructure
  skip_cleanup: true
  user: ducasse
  key:
    secure: zodokrwHz+knnZ5ttaT1Sec7CmadE03MmIVlnwf8ceAS/PKdxuLhBFMMPJOI/NNSVA5j6Z6GQdenvWDWYor01W5G2AGqsVqV8xAIAmfTzcZq9cKcY/oQxq85Uq8N44SWvqEZjTlw5by3SXCIQBMKRRwUwiiLwhXLXlZ2YVzDtOy5DczhKdd0h3f7lhaCEvuJm3HTGIItwbZCk3WXvH81kFmQaolxZqkJuv7OkHmj7sK6S00kq61EVhXAfVsOUm3O+Ls1skwrNcY/ZjJ3l9sKTvyefYelHmerSSWdj+y3fSbo7Hw1YF1XnTwf2zbOfMJB9fZMMo7ejCWyb35wrZDO9yZsUTiouxcdThjGyHqnhAYI+QVRORjefYbWRU6oy0k08pxJfoaUhtVYrZcteuW1/IQpW2bI/p1SHBHlSg8cQ+Q6L+SDEdKzyGl9s+XGgcA1m6KufhYRAakJYse5XfIbzd3uwacVpMwCscJjmjJWvnlGEgnXxVnyiCIhhb0R3ZRTy7BxPV1MIVkZCtn05AjptcjMJgT5lvId+VjrV3aKcxi16dnQa68HoX3p9jgfid1PPiPmA4Z54+x2JOGjClk9QsdMBzxL4mZXT7k+AFvh1zNAc6iOF7wfk6D4LFCfijpCewcH+TJL2YyWPW+HQ46juFdzPNb39rrfWNVM5dNP7jQ=
- provider: releases
  file: build/infrabook.pdf
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: pRfu3fr35BzqQDi1ul0SubPSwO8zcyIidqLRZPz3XIrH4qoy1Zgnq785dmB7ziNQqH+VJyh7askSFY3JLxL0d4P0eUgj2ZDIOhJsUQQ/ihevOBWbxlMOoEPjQfzA11l8WrNCQ566KrcYiISRi7bCg698kPTWSRwOmmvqXOJe5zGkuUbVmMNUV2oxaNV4JC8kVyVWHYy0nNMLEX/hzRZRh1+8K34/ds+fZ7irLrbDWMbKGHCyuLCSqv+zJJdu99nWLTclrCxFzK4DEHaMlFiO7wkUpyQLwZ38EDnb3E7iv045jSqCx3XB+DMRG1Da2/9BIXl0mho5ELdEvfGVAbjI2no5FWd0H1cs4/banAePCFnM7ZscJBaPWgVajB7EzrcADJUoxpmU6+6n1aIC3CnjscfAHqSAKGv8CO/Jh+Uirc8ATRpSqa73f2Nnj9tRCqwCOnFOCEzu0w5l3Ppz2Qpif04P+QbebZehSVaBJ4W01R2i8Rac3IuZDhZVaek1X24HFxUOd/rvHpbhz8eeANdnsWCTkAm+0sD+iKsWKICRMxFZfCK/SPldAcjXZsOsEMTqfx7ZWyCc7GeesQWcmW+z3shziyQd9tdeArJWLwacly3hH3WeyuUD5JyPF9klvDBtHgTVajdU4yp+3oXsrtTmetnBz+RESxQGdLgZRlQBQog=
